### 1. Write a Python Program to Add Two Matrices?

In [1]:
def add_metrices(a,b):
    import numpy as np
    return np.add(a,b)

In [2]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9]]
b = [[1,2,3],
    [4,5,6],
    [7,8,9]]

In [3]:
add_metrices(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

### 2. Write a Python Program to Multiply Two Matrices?

In [4]:
def matrix_multiplication(a,b):
    import numpy as np
    a,b = np.array(a), np.array(b)
    return np.dot(a,b)

In [5]:
a = [[1,2,6],
    [4,2,6],
    [7,5,9]]
b = [[1,2,3],
    [4,2,7],
    [4,7,2]]

In [6]:
try:
    print(matrix_multiplication(a,b))
except Exception as e:
    print(f"\nERROR : {e}.")

[[33 48 29]
 [36 54 38]
 [63 87 74]]


### 3. Write a Python Program to Transpose a Matrix?

In [7]:
def transpose(matrix):
    import numpy as np
    matrix = np.array(matrix)
    return matrix.T

In [8]:
m1 = [[1,2,6],
     [4,2,6],
     [7,5,9]]

In [9]:
transpose(m1)

array([[1, 4, 7],
       [2, 2, 5],
       [6, 6, 9]])

### 4. Write a Python Program to Sort Words in Alphabetic Order?

In [31]:
def word_sort():
    st = input("Enter some words : ")
    l1 = st.split(" ")
    l1.sort()
    return f"\nHere are sorted words : {' '.join(l1)}"

In [44]:
try:
    print(word_sort())
except Exception as e:
    print(f"\nERROR : {e}.")

Enter some words : i am a good boy

Here are sorted words : a am boy good i


### 5. Write a Python Program to Remove Punctuation From a String?

In [51]:
def punctuation_remover():
    st = input()
    result = ''
    for i in st:
        if i == " ":
            result += i
            continue
        if i.isalnum():
            result += i
    return result

In [53]:
punctuation_remover()

hello there, i am a python learner. thank you!


'hello there i am a python learner thank you'